### ISSUE TITLE
`figcaption` improvements

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#380]
Centers the caption when it is less than one line length, then left aligns longer captions.

```css
figcaption {
  max-inline-size: max-content;
  margin-inline: auto;
}
```
