### ISSUE TITLE
Opt-in to view transitions

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#381]
We can opt-in to [smooth page transitions](https://developer.chrome.com/docs/web-platform/view-transitions/) for users that are OK with animations with this snippet in the theme:

```css
@media (prefers-reduced-motion: no-preference) {
  @view-transition {
    navigation: auto;
  }
}
```
